# Generated by Django 2.0.1 on 2018-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bumped',
            field=models.BooleanField(default=False),
        ),
    ]
