# Generated by Django 2.0.1 on 2018-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_ticket_bumped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
