# Generated by Django 2.0.1 on 2018-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20180224_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight_no',
            field=models.CharField(default=123, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
